spring:
   mail:
    host: smtp.gmail.com
    port: 587    
    username: c0433c@gmail.com
    password: rl11xo22
    properties:
      mail:    
        smtp:
          auth: true
          starttls.enable: true
      